name: flutter_cpf
description: An example on how to use the cpf_util with a Flutter project.
version: 0.1.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  cpf_utility:
    path: ../

flutter:
  uses-material-design: true
