name: cpf_utility
description: Generate, validate and format valid Brazilian CPF's.
repository: https://github.com/duffhd/cpf_util
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
