name: cpf_utility
description: A simple package to generate, validate and format valid Brazilian CPF's, it supports creating totally random CPF's or creating CPF's out of a specific state.
repository: https://github.com/duffhd/cpf_util
version: 1.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
