name: cpf_cli
description: A very simple cli utility that wraps the cpf_utility library.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cpf_utility: ^1.0.1

dev_dependencies:
  lints: ^1.0.0
